services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gamdom_test_frontend
      - gamdom_test_backend
    networks:
      - gamdom_network

  gamdom_test_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - gamdom_network
    environment:
      - VITE_HOST_API=http://nginx
      - VITE_API_VERSION=1
      - MODE=prod
      - VITE_DEFAULT_USER_EMAIL=falcescu.alin@gmail.com
      - VITE_DEFAULT_USER_PASSWORD=Test1234_

  gamdom_test_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - gamdom_network
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=example_user
      - DB_PASSWORD=example_password
      - DB_NAME=gamdom_test

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: gamdom_test
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - gamdom_network

networks:
  gamdom_network:

volumes:
  db_data:
